name: Build and Release APK

on:
  push:
    branches:
      - main

# Add permissions for the workflow
permissions:
  contents: write  # Required for creating releases
  packages: write  # Required for uploading release assets

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for the release action to work properly

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Build APK
        run: |
          flutter clean
          flutter pub get
          flutter build apk --release --dart-define=APP_VERSION=$(git describe --tags --abbrev=0 || echo 'v0.0.0')

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v$(grep 'version:' pubspec.yaml | cut -d' ' -f2 | tr -d '+').${{ github.run_number }}
          name: 'Release v$(grep 'version:' pubspec.yaml | cut -d' ' -f2 | tr -d '+').${{ github.run_number }}'
          body: 'Automated release from GitHub Actions'
          files: |
            build/app/outputs/flutter-apk/app-release.apk
          draft: false
          prerelease: false